### ISSUE TITLE
Logger... 

### ISSUE THREAD

**Issue by angelru** [CodeMazeBlog/global-error-handling-aspnetcore#3]
Hello,

```
InvalidOperationException: No service for type 'NLog.ILogger' has been registered.
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)

Exception: Could not resolve a service of type 'NLog.ILogger' for the parameter 'logger' of method 'Configure' on type 'AppBack.Startup'.
Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(object instance, IApplicationBuilder builder)

InvalidOperationException: No service for type 'NLog.ILogger' has been registered.

```
any solution?

`      public void Configure(IApplicationBuilder app, ILogger logger)`

**Comment by shakerkamal** [comment]
Can you please share your code or Startup.cs file? From what I can see, you are trying to log the incoming requests. In the demonstrated code they have done logging on data access from database. 

Try this code : 
`public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILogger<Startup> logger)`

If it doesn't work, then please share your code.
